[linux]
coldPath = $SPLUNK_DB/linux/colddb
homePath = $SPLUNK_DB/linux/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/linux/thaweddb

[ad]
coldPath = $SPLUNK_DB/ad/colddb
homePath = $SPLUNK_DB/ad/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/ad/thaweddb

[windows]
coldPath = $SPLUNK_DB/windows/colddb
homePath = $SPLUNK_DB/windows/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/windows/thaweddb
