[general]
serverName = localhost.localdomain
pass4SymmKey = $7$6mn0Ft4muHnpFOIj3blB8r85k2lfVk3+cjVCkdgnrWXaCgj7wM1Btw==

[sslConfig]
sslPassword = $7$JNa6KPEAQ0ZkZI/fW9f7vJKPjdwjzuYg08LSUNnobS4A4L1Klq5nZA==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
